[package]
name = "irontest"
version = "0.1.0"
authors = ["Andrei Nagacevschi andrein_bio@yahoo.com"]

[dependencies]
iron="*"
router="*"
serde="*"
serde_json="*"
serde_derive="*"
staticfile="*"
mount="*"
toml="*"
rustview= {path = "../rustview"}
